#!/bin/bash

if [ "$#" -eq 0 ]; then
  echo "Usage: $0 CIPHERED_FOLDERS_AND_FILES" >&2
  exit 1
fi

for f in "$@"; do
  if [ ! -f "$f" ]; then
    echo "Not a file: $f" >&2
    exit 1
  fi

  echo "Deciphering $f"
  if [[ "$f" == *.tar.gz.gpg ]]; then
    gpg -d 2>/dev/null <(pv "$f") | tar -xz
  else
    gpg -d 2>/dev/null -o "${f%.gpg}" <(pv "$f")
  fi
done
