#!/bin/bash

print_usage() {
  echo "Usage: $0 [-x] [-o output_folder] CIPHERED_FOLDERS_AND_FILES" >&2
}

#############
### Flags ###
#############

extract=false
output=.

while getopts 'xo:' flag; do
  case "${flag}" in
    x) extract=true ;; # Do we try to auto extract?
    o) output="$OPTARG" ;; # Custom output folder
    *) print_usage
       exit 1 ;;
  esac
done

shift $(($OPTIND - 1)) # shift to positionnal arguments

############
### Args ###
############

if [ "$#" -eq 0 ]; then
  print_usage
  exit 1
fi
if [ ! -d "$output" ]; then
  echo "$0: $output: Cannot open: No such directory"
  exit 1
fi

############
### Main ###
############

for f in "$@"; do
  # Check if the arg is a file, in case it got deleted during deciphering of previous files
  if [ ! -f "$f" ]; then
    echo "$0: $f: Cannot open: No such file" >&2
    exit 1
  fi

  echo "Deciphering $f" >&2
  # If the file corresponds to a ciphered folder and we asked to extract
  if [[ "$f" == *.tar.gz.gpg ]] && [[ $extract == true ]]; then
    gpg -d 2>/dev/null <(pv "$f") | tar -xzC "$output"
  # Default, just decipher and remove .gpg file extension
  else
    gpg -d 2>/dev/null -o "$output/$(basename "${f%.gpg}")" <(pv "$f")
  fi
done
